import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";

const VideoThumbNailGenerator = dynamic(
 () => import("../components/videoThumbNailGenderator/VideoThumbNailGenerator"),
 {
  ssr: false,
 }
);

import styles from "../styles/Home.module.css";
import { useState } from "react";
import { IEditData } from "../components/videoThumbNailGenderator/helpers/eidtVidoe";

const Home: NextPage = () => {
 const [editOpen, setEditOpen] = useState(false);
 const [editInfo, seteditInfo] = useState<IEditData>({
  end: 350,
  start: 0,
  selectOf: 3,
  selectSkip: 60,
  width: 480,
  skipAudio: true,
  quality: 35,
 });

 return (
  <div
   style={{
    display: "flex",
    justifyContent: "center",
   }}
  >
   <div className="mt-20 container px-4 max-w-lg">
    <Head>
     <title>Create Next App</title>
     <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/favicon.ico" />
    </Head>

    <article className=" prose lg:prose-lg">
     <h1>동영상 썸네일 제조기</h1>
     <b>동영상을 여기 업로드하시면 최적화된 동영상 썸네일을 제작해 드립니다.</b>
     <h3>기본규칙</h3>
     <ul>
      <li>3초 수집 후 60초 생략 반복 (15초가 최대) </li>
      <li>썸네일 크기 가로 450px 세로 비율자동</li>
      <li>오디오 생략</li>
      <li>퀄리티 하향조절</li>
     </ul>
    </article>
    <button
     onClick={() => {
      setEditOpen(true);
     }}
     className="border disabled:opacity-50 border-gray-300 hover:bg-gray-100 mb-10 p-2.5 w-1/3 flex items-center justify-center rounded-md"
    >
     설정 수정하기
    </button>
    <VideoThumbNailGenerator
     editOpen={editOpen}
     setEditOpen={setEditOpen}
     editInfo={editInfo}
     seteditInfo={seteditInfo}
    />

    <footer className={styles.footer}>
     <a
      href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      target="_blank"
      rel="noopener noreferrer"
     >
      Powered by <b className="ml-1">SuperWallaby</b>
     </a>
    </footer>
   </div>
  </div>
 );
};

export default Home;
